FROM node:10-alpine

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

RUN apk update
RUN apk --no-cache add bash python make g++

#ARG DBUILDER_WORKDIR

#WORKDIR /srctesting

# install dependencies? 
# - TODO 

# dunno, shot in the dark
#COPY . /srctesting

RUN echo "TESTING HERE1"
RUN ls -al /usr/src/attached-volume

RUN npm i -g http-server 

CMD [ "http-server" ]
